console.log(3 != 3)
console.log(5 != 3)
console.log(5 != "5")
console.log(5 != 3)
console.log(5 !== "5")
console.log(4 > 3)
console.log(5 > 10)
console.log(5 >= 5)
console.log(6 <= 3)
console.log(6 < 6)

